name: fforestimator
description: Une application cartographique pour les forestiers wallons qui permet d'obtenir de nombreux renseignements sur les stations forestières et sur les peuplements en place.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.0+22

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  flutter_map: ^8.0.0
  path_provider: ^2.1.2
  http: ^1.0.0
  tuple: ^2.0.2
  flutter_downloader: ^1.12.0
  geolocator: ^14.0.0
  connectivity_plus: ^7.0.0 # te dis si tu es connecté au wifi ou à la data, mais pas si tu as accès à internet. pas suffisant donc
  internet_connection_checker_plus: ^2.3.0
  latlong2: ^0.9.0
  go_router: ^16.2.1
  flutter_pdfview: ^1.2.7
  flutter_map_location_marker: ^10.1.0
  image: ^4.5.4
  geoimage: ^0.4.0
  shared_preferences: ^2.2.2
  pdf: ^3.10.8
  intl: ^0.20.2
  downloadsfolder: ^1.1.0
  permission_handler: ^12.0.0+1
  memory_info: ^0.0.4
  device_info_plus: ^12.1.0
  proj4dart: ^2.1.0
  area_polygon: ^1.0.2
  archive: ^4.0.7
  dart_jts: ^0.3.0+1
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
# Here i try to solve an issue that occurs while compiling for iOS - JL I comment that to compile in apk
#  dependency_overrides:
#  win32: ^5.5.0
# end:

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
     - assets/db/fforestimator.db
     - assets/images/
     - assets/fichesEss/
     - assets/pdf/
     - assets/GSA/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/myIcons.ttf
