name: fforestimator
description: Une application cartographique pour les forestiers wallons qui permet d'obtenir de nombreux renseignements sur les stations forestières et sur les peuplements en place.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.9.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  provider: ^6.1.1
  sqflite_common_ffi: ^2.3.2
  sidebarx: ^0.17.1
  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0
  url_launcher: ^6.2.3
  path_provider: ^2.1.2
  http: ^1.0.0
  tuple: ^2.0.2
  flutter_downloader: ^1.11.6
  geolocator: ^11.0.0 
  geolocator_linux: ^0.2.0+1 # la version geolocator_linux de geolocator 10.1 est la 0.1.3 buggée
  connectivity_plus: ^6.0.1 # te dis si tu es connecté au wifi ou à la data, mais pas si tu as accès à internet. pas suffisant donc
  internet_connection_checker_plus: ^2.3.0
  latlong2: ^0.9.0
  flutter_sensors: ^1.0.1
  go_router: ^13.2.0
  flutter_pdfview: ^1.2.7

  #dependency_overrides: # geoimage et pdf utilise ce package tout les deux.
  image: ^4.1.7
    #path: ../image/
    #git:
      #url: https://github.com/brendan-duncan/image.git
      #ref: main # commit hash
      #version: ^4.1.7

  geoimage: ^0.4.0
  shared_preferences: ^2.2.2
  pdf: ^3.10.8
  flutter_logs: ^2.1.11
  intl: ^0.19.0
  downloadsfolder: ^0.1.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
     - assets/db/fforestimator.db
     - assets/images/
     - assets/fichesEss/
     - assets/pdf/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/myIcons.ttf
